# Generated by Django 4.2.5 on 2024-10-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ntn',
            field=models.CharField(default=694866286, max_length=10, unique=True),
        ),
    ]
