# Generated by Django 4.2.5 on 2024-10-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_ntn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ntn',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
