# Generated by Django 4.2.5 on 2024-10-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_address_userprofile_address1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='industry_type',
            field=models.CharField(choices=[('aerospace', 'Aerospace'), ('agriculture', 'Agriculture'), ('apparel/textile', 'Apparel/Textile'), ('automotive', 'Automotive'), ('banking', 'Banking'), ('chemical_manufacturing', 'Chemical_Manufacturing'), ('construction/contrating', 'Construction/Contrating'), ('consulting', 'Consulting'), ('consumer_goods', 'Consumer_Goods'), ('defence', 'Defence'), ('e_commerce', 'E_Commerce'), ('education', 'Education'), ('energy/oil_gas', 'Energy/Oil_Gas'), ('engineering', 'Engineering'), ('entertainment', 'Entertainment'), ('event_management', 'Event_Management'), ('food_beverages', 'Food_Beverages'), ('govt/utilties', 'Govt/Utilities'), ('healthcare/pharma', 'Healthcare/Pharma'), ('heavy_equipment', 'Heavy_Equipment'), ('it/software/ai', 'IT/Software/AI'), ('journalism', 'Journalism'), ('legal_services', 'Legal_Services'), ('logistic', 'Logistic'), ('mining', 'Mining'), ('real_estate', 'Real_Estate'), ('retail', 'Retail'), ('sports', 'Sports'), ('telecom', 'Telecom'), ('tourism', 'Tourism'), ('other', 'Other')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='no_of_employees',
            field=models.PositiveIntegerField(choices=[('1-10', '1-10'), ('11-25', '11-25'), ('26-50', '26-50'), ('50-100', '50-100'), ('100-500', '100-500'), ('500+', '500+')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
