# Generated by Django 4.2.5 on 2024-10-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userprofile_business_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='industry_type',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='no_of_employees',
            field=models.PositiveIntegerField(choices=[(1, '1-10'), (11, '11-25'), (26, '26-50'), (51, '50-100'), (101, '100-500'), (501, '500+')]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='industry_type',
            field=models.ManyToManyField(related_name='user_profiles', to='users.industry'),
        ),
    ]
