# Generated by Django 4.2.5 on 2024-10-20 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_industry_remove_userprofile_industry_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='business_type',
            field=models.CharField(blank=True, choices=[('trader/wholeseller/distributor', 'Trader/WholeSeller/Distributor'), ('manufacturer', 'Manufacturer'), ('service organization', 'Service Organization')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='establishment_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='industry_type',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_profiles', to='users.industry'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='no_of_employees',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1-10'), (11, '11-25'), (26, '26-50'), (51, '50-100'), (101, '100-500'), (501, '500+')], null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('sole properietor', 'Sole Proprietor'), ('partnership', 'Partnership'), ('private limited', 'Private Limited'), ('public limited', 'Public Limited')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
