# Generated by Django 4.2.5 on 2024-10-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_userprofile_business_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='industry_type',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='users.industry'),
        ),
    ]
