# Generated by Django 4.2.5 on 2024-10-21 10:26

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0011_alter_userprofile_industry_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=100)),
                ('product_model', models.CharField(max_length=100)),
                ('manufacturing_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2024)])),
                ('hours_operation', models.PositiveIntegerField()),
                ('product_location', models.CharField(max_length=200)),
                ('product_description', models.TextField(max_length=500)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('product_images', sorl.thumbnail.fields.ImageField(upload_to='products')),
                ('industry', models.ManyToManyField(related_name='industry_products', to='users.industry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
