# Generated by Django 4.2.5 on 2024-10-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_brand',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
