# Generated by Django 4.2.5 on 2024-10-31 04:28

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_images',
            field=sorl.thumbnail.fields.ImageField(upload_to='products'),
        ),
    ]
